---
apiVersion: v1
kind: Namespace
metadata:
  name: whois

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whois
  namespace: whois
  labels:
    name: whois
spec:
  replicas: 4
  selector:
    matchLabels:
      name: whois
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        name: whois
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: msfidelis/whois:v1
        name: whois
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080        
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "256m"
            memory: "512m"

---
kind: Service
apiVersion: v1
metadata:
  name: whois
  namespace: whois
spec:
  selector:
    name: whois
  ports:
    - protocol: TCP
      port: 8080
      name: web
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whois
  namespace: whois
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: whois
    hosts:
    - whois.raj.ninja
  rules:
  - http:
      paths:
      - path: /whois
        backend:
          serviceName: whois
          servicePort: 8080
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: whois
  namespace: whois
spec:
  virtualhost:
    fqdn: whois.raj.ninja
    tls:
      secretName: whois
  routes:
  - services:
    - name: whois
      port: 8080
